#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NavDrawer.Forms.Resource", IsApplication=true)]

namespace NavDrawer.Forms
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_drawer_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_refresh = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
